### ISSUE TITLE
Use CSS variables

### ISSUE THREAD

**Issue by arturdryomov** [yawpitch/base16-hugo#1]
Not sure if it is the right way to do things with how Base16 works but seems to be worth a try. 

* Variables are supported on a pretty [good range of browser versions](https://caniuse.com/#feat=css-variables).
* It allows to use `prefers-color-scheme` stupid-easy since it will be just a variables swap. Currently [I did a color replacement](https://github.com/ming13/pages/blob/5b6b5937d5f076428177564b807d9aec26d22125/themes/barebones/static/css/syntax-highlighting.css) manually to achieve this.
* Probably it will be a more efficient process since only 16 replacements needs to be made instead of `N` Pygments / Chroma directives.

**Comment by yawpitch** [comment]
If I _weren't_ using Base16's builder I'd agree; as I am the variables are in the templates/default.mustache and it builds out all the various hard-coded permutations for each color scheme. Having hard-coded files in the end seems to be a design feature of Base16 here.

**Comment by ttys3** [comment]
@arturdryomov  wow, that's awesome! thanks
